# sass-lint config
#
# For all rules, setting their severity to 0 turns it off,
# setting to 1 sets it as a warning,
# and setting to 2 sets it to an error.
#
# These properties are documented at
# https://github.com/sasstools/sass-lint/tree/master/docs/rules

files:
  include: "src/assets/css/**/*.scss"
  ignore:
    - "src/assets/css/_boilerplate.scss"
    - "src/assets/css/_normalize.scss"
    - "src/assets/css/_print.scss"
    - "src/assets/css/combined/**/*.scss"
options:
  formatter: stylish
  merge-default-rules: false
rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals:
     - 1
     - allow-rgba: true
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties:
    - 1
    - exclude: ["font-size", "line-height", "letter-spacing", "cursor"]
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 1
    - extra-properties: ["border-"]
  no-qualifying-elements: 0
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes:
    - 1
    - ignore-non-standard: true
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 0
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  bem-depth: 0
  border-zero: 0
  brace-style:
    - 1
    - allow-single-line: true
  clean-import-paths: 0
  empty-args: 0
  hex-length: 0
  hex-notation:
    - 1
    - style: uppercase
  indentation:
    - 1
    - size: 'tab'
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 5
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
